---
- name: Get all matching alerts.
  shell: >
    curl {{ alertmanager_url | default('alertmanager.it.svc.cluster.local:9093') }}/api/v1/silences | jq -r '.data[] | select(.matchers[].name == "{{ alertmanager_silence_label_name }}" and .matchers[].value == "{{ alertmanager_silence_label_value }}" and .status.state == "active") | .id'
  register: active_silences

- name: Debug Alertmanager silences.
  debug:
    msg: "{{ item }}"
  with_items: "{{ active_silences.stdout_lines }}"

- name: Remove matching silences.
  uri:
    url: "http://{{ alertmanager_url | default('alertmanager.it.svc.cluster.local:9093') }}/api/v1/silence/{{ item }}"
    method: DELETE
    status_code: 200
  when: active_silences.stdout_lines | length > 0
  with_items: "{{ active_silences.stdout_lines }}"
