route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack_info
  routes:
  - match_re:
      severity: 'warning'
    receiver: slack_info
# inhibit_rules:
# - source_match:
#     severity: 'critical'
#   target_match:
#     severity: 'warning'
#   equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'pagerduty'
  pagerduty_configs:
  - service_key: ${PAGERDUTY_API_KEY}
# Reference: https://medium.com/quiq-blog/better-slack-alerts-from-prometheus-49125c8c672b
- name: 'slack_info'
  slack_configs:
  - api_url: ${SLACK_WEB_HOOK}
    channel: '#slacktest'
    send_resolved: true
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_text" . }}'
    # text: "*Severity:* {{ .CommonLabels.severity }}\n*Message:* {{ (index .Alerts 0).Annotations.message }}\n*Runbook:* {{ .CommonAnnotations.runbook_url }}"
templates:
- '/opt/template/*.tmpl'
