apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
      name: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.12.0
        ports:
        - containerPort: 9115
          name: blackbox
          protocol: TCP
        resources:
          requests:
            cpu: .1
            memory: 128M
          limits:
            cpu: .5
            memory: 512M
        volumeMounts:
        - mountPath: /etc/blackbox_exporter
          name: blackbox-exporter-config
          readOnly: true
      volumes:
      - name: blackbox-exporter-config
        configMap:
          defaultMode: 420
          name: blackbox-exporter-config

