controller:
  ingressClass: monitoring
  lifecycle:
    preStop:
      exec:
        command: ["sleep", "20"]
  metrics:
    enabled: true
    service:
      annotations: {
        prometheus.io/port: "10254",
        prometheus.io/scrape: "true"
      }
  replicaCount: 3
  stats:
    enabled: true
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
