kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: dev
rules:
- apiGroups:
  - extensions
  - ""
  resources:
  - configmaps
  - ingresses
  - containers
  - pods/exec
  - deployments
  - deployments/rollback
  - rollouts
  - events
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - post
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-delete-ingress
  namespace: dev
rules:
- apiGroups:
  - extensions
  - ""
  resources:
  - ingresses
  verbs:
  - delete
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - get
  - list
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: dev
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: dev
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-delete-ingress
  namespace: dev
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: dev
roleRef:
  kind: Role
  name: jenkins-delete-ingress
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: monitoring
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: monitoring
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
