kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - get
  - list
  - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: it
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods/portforward
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - post
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: monitoring
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: monitoring
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: it
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: it
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
