route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack_warning
  routes:
  - match_re:
      severity: 'critical'
    receiver: pagerduty
  - match_re:
      severity: 'warning'
    receiver: slack_warning
  - match_re:
      severity: 'webhook'
    receiver: webhook
# inhibit_rules:
# - source_match:
#     severity: 'critical'
#   target_match:
#     severity: 'warning'
#   equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'pagerduty'
  pagerduty_configs:
  - service_key: ${PAGERDUTY_API_KEY}
# Reference: https://medium.com/quiq-blog/better-slack-alerts-from-prometheus-49125c8c672b
- name: 'slack_warning'
  slack_configs:
  - api_url: ${SLACK_WEB_HOOK}
    send_resolved: true
    channel: '#prometheus'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_text" . }}'
- name: 'webhook'
  webhook_configs:
  - url: http://alerthooks.jenkins.svc.cluster.local:5000
    send_resolved: false
    http_config:
      bearer_token: ${BEARER_TOKEN}
templates:
- '/opt/template/*.tmpl'
