---
# stop services from starting automatically
- name: Copy policy-rc.d file (to stop dpkg from autostarting services).
  copy:
    content: "#!/bin/sh\necho 'All runlevel operations denied by policy' >&2\nexit 101"
    dest: /usr/sbin/policy-rc.d
    mode: 0755

- name: Install apt packages (if defined).
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages | default([])  }}"
  when: apt_packages is defined

- name: Install pip packages (if defined).
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages | default([])  }}"
  when: pip_packages is defined

- name: Install npm packages (if defined).
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ npm_packages | default([]) }}"
  when: npm_packages is defined

- name: Prevent auto-update
  command: /bin/sed -ie 's/APT::Periodic::Unattended-Upgrade "1";/APT::Periodic::Unattended-Upgrade "0";/g' /etc/apt/apt.conf.d/20auto-upgrades

